// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package billscan

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "github.com/golang/protobuf/ptypes/wrappers"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Agreement_Status int32

const (
	Agreement_PENDING      Agreement_Status = 0
	Agreement_ACKNOWLEDGED Agreement_Status = 1
	Agreement_DENIED       Agreement_Status = 2
)

var Agreement_Status_name = map[int32]string{
	0: "PENDING",
	1: "ACKNOWLEDGED",
	2: "DENIED",
}

var Agreement_Status_value = map[string]int32{
	"PENDING":      0,
	"ACKNOWLEDGED": 1,
	"DENIED":       2,
}

func (x Agreement_Status) String() string {
	return proto.EnumName(Agreement_Status_name, int32(x))
}

func (Agreement_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3, 0}
}

type Relation struct {
	Id                   string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               string            `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ContactId            string            `protobuf:"bytes,3,opt,name=contact_id,json=contactId,proto3" json:"contact_id,omitempty"`
	CreatedAt            uint64            `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            uint64            `protobuf:"varint,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ContactProfile       *Relation_Profile `protobuf:"bytes,6,opt,name=contact_profile,json=contactProfile,proto3" json:"contact_profile,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Relation) Reset()         { *m = Relation{} }
func (m *Relation) String() string { return proto.CompactTextString(m) }
func (*Relation) ProtoMessage()    {}
func (*Relation) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *Relation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Relation.Unmarshal(m, b)
}
func (m *Relation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Relation.Marshal(b, m, deterministic)
}
func (m *Relation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Relation.Merge(m, src)
}
func (m *Relation) XXX_Size() int {
	return xxx_messageInfo_Relation.Size(m)
}
func (m *Relation) XXX_DiscardUnknown() {
	xxx_messageInfo_Relation.DiscardUnknown(m)
}

var xxx_messageInfo_Relation proto.InternalMessageInfo

func (m *Relation) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Relation) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Relation) GetContactId() string {
	if m != nil {
		return m.ContactId
	}
	return ""
}

func (m *Relation) GetCreatedAt() uint64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Relation) GetUpdatedAt() uint64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *Relation) GetContactProfile() *Relation_Profile {
	if m != nil {
		return m.ContactProfile
	}
	return nil
}

type Relation_Profile struct {
	DisplayName          string   `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Relation_Profile) Reset()         { *m = Relation_Profile{} }
func (m *Relation_Profile) String() string { return proto.CompactTextString(m) }
func (*Relation_Profile) ProtoMessage()    {}
func (*Relation_Profile) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0, 0}
}

func (m *Relation_Profile) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Relation_Profile.Unmarshal(m, b)
}
func (m *Relation_Profile) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Relation_Profile.Marshal(b, m, deterministic)
}
func (m *Relation_Profile) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Relation_Profile.Merge(m, src)
}
func (m *Relation_Profile) XXX_Size() int {
	return xxx_messageInfo_Relation_Profile.Size(m)
}
func (m *Relation_Profile) XXX_DiscardUnknown() {
	xxx_messageInfo_Relation_Profile.DiscardUnknown(m)
}

var xxx_messageInfo_Relation_Profile proto.InternalMessageInfo

func (m *Relation_Profile) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

type User struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Mobile               string   `protobuf:"bytes,2,opt,name=mobile,proto3" json:"mobile,omitempty"`
	ProfileImage         string   `protobuf:"bytes,3,opt,name=profile_image,json=profileImage,proto3" json:"profile_image,omitempty"`
	DisplayName          string   `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Registered           bool     `protobuf:"varint,5,opt,name=registered,proto3" json:"registered,omitempty"`
	CreatedAt            uint64   `protobuf:"varint,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            uint64   `protobuf:"varint,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	SignImage            string   `protobuf:"bytes,8,opt,name=sign_image,json=signImage,proto3" json:"sign_image,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *User) GetProfileImage() string {
	if m != nil {
		return m.ProfileImage
	}
	return ""
}

func (m *User) GetDisplayName() string {
	if m != nil {
		return m.DisplayName
	}
	return ""
}

func (m *User) GetRegistered() bool {
	if m != nil {
		return m.Registered
	}
	return false
}

func (m *User) GetCreatedAt() uint64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *User) GetUpdatedAt() uint64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *User) GetSignImage() string {
	if m != nil {
		return m.SignImage
	}
	return ""
}

type Bill struct {
	Id                   string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ImageUrl             string     `protobuf:"bytes,2,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	BillFrom             string     `protobuf:"bytes,3,opt,name=bill_from,json=billFrom,proto3" json:"bill_from,omitempty"`
	BillTo               string     `protobuf:"bytes,4,opt,name=bill_to,json=billTo,proto3" json:"bill_to,omitempty"`
	CreatedAt            uint64     `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            uint64     `protobuf:"varint,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Agreement            *Agreement `protobuf:"bytes,7,opt,name=agreement,proto3" json:"agreement,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Bill) Reset()         { *m = Bill{} }
func (m *Bill) String() string { return proto.CompactTextString(m) }
func (*Bill) ProtoMessage()    {}
func (*Bill) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *Bill) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bill.Unmarshal(m, b)
}
func (m *Bill) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bill.Marshal(b, m, deterministic)
}
func (m *Bill) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bill.Merge(m, src)
}
func (m *Bill) XXX_Size() int {
	return xxx_messageInfo_Bill.Size(m)
}
func (m *Bill) XXX_DiscardUnknown() {
	xxx_messageInfo_Bill.DiscardUnknown(m)
}

var xxx_messageInfo_Bill proto.InternalMessageInfo

func (m *Bill) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Bill) GetImageUrl() string {
	if m != nil {
		return m.ImageUrl
	}
	return ""
}

func (m *Bill) GetBillFrom() string {
	if m != nil {
		return m.BillFrom
	}
	return ""
}

func (m *Bill) GetBillTo() string {
	if m != nil {
		return m.BillTo
	}
	return ""
}

func (m *Bill) GetCreatedAt() uint64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Bill) GetUpdatedAt() uint64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *Bill) GetAgreement() *Agreement {
	if m != nil {
		return m.Agreement
	}
	return nil
}

type Agreement struct {
	Note                 string           `protobuf:"bytes,1,opt,name=note,proto3" json:"note,omitempty"`
	Status               Agreement_Status `protobuf:"varint,2,opt,name=status,proto3,enum=okcredit.billscan.v1.Agreement_Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *Agreement) Reset()         { *m = Agreement{} }
func (m *Agreement) String() string { return proto.CompactTextString(m) }
func (*Agreement) ProtoMessage()    {}
func (*Agreement) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *Agreement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Agreement.Unmarshal(m, b)
}
func (m *Agreement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Agreement.Marshal(b, m, deterministic)
}
func (m *Agreement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Agreement.Merge(m, src)
}
func (m *Agreement) XXX_Size() int {
	return xxx_messageInfo_Agreement.Size(m)
}
func (m *Agreement) XXX_DiscardUnknown() {
	xxx_messageInfo_Agreement.DiscardUnknown(m)
}

var xxx_messageInfo_Agreement proto.InternalMessageInfo

func (m *Agreement) GetNote() string {
	if m != nil {
		return m.Note
	}
	return ""
}

func (m *Agreement) GetStatus() Agreement_Status {
	if m != nil {
		return m.Status
	}
	return Agreement_PENDING
}

type ListContactsRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListContactsRequest) Reset()         { *m = ListContactsRequest{} }
func (m *ListContactsRequest) String() string { return proto.CompactTextString(m) }
func (*ListContactsRequest) ProtoMessage()    {}
func (*ListContactsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4}
}

func (m *ListContactsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListContactsRequest.Unmarshal(m, b)
}
func (m *ListContactsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListContactsRequest.Marshal(b, m, deterministic)
}
func (m *ListContactsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListContactsRequest.Merge(m, src)
}
func (m *ListContactsRequest) XXX_Size() int {
	return xxx_messageInfo_ListContactsRequest.Size(m)
}
func (m *ListContactsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListContactsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListContactsRequest proto.InternalMessageInfo

func (m *ListContactsRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type ListContactsResponse struct {
	Contacts             []*User  `protobuf:"bytes,1,rep,name=contacts,proto3" json:"contacts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListContactsResponse) Reset()         { *m = ListContactsResponse{} }
func (m *ListContactsResponse) String() string { return proto.CompactTextString(m) }
func (*ListContactsResponse) ProtoMessage()    {}
func (*ListContactsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{5}
}

func (m *ListContactsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListContactsResponse.Unmarshal(m, b)
}
func (m *ListContactsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListContactsResponse.Marshal(b, m, deterministic)
}
func (m *ListContactsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListContactsResponse.Merge(m, src)
}
func (m *ListContactsResponse) XXX_Size() int {
	return xxx_messageInfo_ListContactsResponse.Size(m)
}
func (m *ListContactsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListContactsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListContactsResponse proto.InternalMessageInfo

func (m *ListContactsResponse) GetContacts() []*User {
	if m != nil {
		return m.Contacts
	}
	return nil
}

type AddContactRequest struct {
	Contact              *User    `protobuf:"bytes,1,opt,name=contact,proto3" json:"contact,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddContactRequest) Reset()         { *m = AddContactRequest{} }
func (m *AddContactRequest) String() string { return proto.CompactTextString(m) }
func (*AddContactRequest) ProtoMessage()    {}
func (*AddContactRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{6}
}

func (m *AddContactRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddContactRequest.Unmarshal(m, b)
}
func (m *AddContactRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddContactRequest.Marshal(b, m, deterministic)
}
func (m *AddContactRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddContactRequest.Merge(m, src)
}
func (m *AddContactRequest) XXX_Size() int {
	return xxx_messageInfo_AddContactRequest.Size(m)
}
func (m *AddContactRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddContactRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddContactRequest proto.InternalMessageInfo

func (m *AddContactRequest) GetContact() *User {
	if m != nil {
		return m.Contact
	}
	return nil
}

func (m *AddContactRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type AddContactResponse struct {
	Contact              *User    `protobuf:"bytes,1,opt,name=contact,proto3" json:"contact,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddContactResponse) Reset()         { *m = AddContactResponse{} }
func (m *AddContactResponse) String() string { return proto.CompactTextString(m) }
func (*AddContactResponse) ProtoMessage()    {}
func (*AddContactResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{7}
}

func (m *AddContactResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddContactResponse.Unmarshal(m, b)
}
func (m *AddContactResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddContactResponse.Marshal(b, m, deterministic)
}
func (m *AddContactResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddContactResponse.Merge(m, src)
}
func (m *AddContactResponse) XXX_Size() int {
	return xxx_messageInfo_AddContactResponse.Size(m)
}
func (m *AddContactResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddContactResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddContactResponse proto.InternalMessageInfo

func (m *AddContactResponse) GetContact() *User {
	if m != nil {
		return m.Contact
	}
	return nil
}

type UpdateContactRequest struct {
	Contact              *User    `protobuf:"bytes,1,opt,name=contact,proto3" json:"contact,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateContactRequest) Reset()         { *m = UpdateContactRequest{} }
func (m *UpdateContactRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateContactRequest) ProtoMessage()    {}
func (*UpdateContactRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{8}
}

func (m *UpdateContactRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateContactRequest.Unmarshal(m, b)
}
func (m *UpdateContactRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateContactRequest.Marshal(b, m, deterministic)
}
func (m *UpdateContactRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateContactRequest.Merge(m, src)
}
func (m *UpdateContactRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateContactRequest.Size(m)
}
func (m *UpdateContactRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateContactRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateContactRequest proto.InternalMessageInfo

func (m *UpdateContactRequest) GetContact() *User {
	if m != nil {
		return m.Contact
	}
	return nil
}

func (m *UpdateContactRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type UpdateContactResponse struct {
	Contact              *User    `protobuf:"bytes,1,opt,name=contact,proto3" json:"contact,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateContactResponse) Reset()         { *m = UpdateContactResponse{} }
func (m *UpdateContactResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateContactResponse) ProtoMessage()    {}
func (*UpdateContactResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{9}
}

func (m *UpdateContactResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateContactResponse.Unmarshal(m, b)
}
func (m *UpdateContactResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateContactResponse.Marshal(b, m, deterministic)
}
func (m *UpdateContactResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateContactResponse.Merge(m, src)
}
func (m *UpdateContactResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateContactResponse.Size(m)
}
func (m *UpdateContactResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateContactResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateContactResponse proto.InternalMessageInfo

func (m *UpdateContactResponse) GetContact() *User {
	if m != nil {
		return m.Contact
	}
	return nil
}

type DeleteContactRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ContactId            string   `protobuf:"bytes,2,opt,name=contact_id,json=contactId,proto3" json:"contact_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteContactRequest) Reset()         { *m = DeleteContactRequest{} }
func (m *DeleteContactRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteContactRequest) ProtoMessage()    {}
func (*DeleteContactRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{10}
}

func (m *DeleteContactRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteContactRequest.Unmarshal(m, b)
}
func (m *DeleteContactRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteContactRequest.Marshal(b, m, deterministic)
}
func (m *DeleteContactRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteContactRequest.Merge(m, src)
}
func (m *DeleteContactRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteContactRequest.Size(m)
}
func (m *DeleteContactRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteContactRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteContactRequest proto.InternalMessageInfo

func (m *DeleteContactRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *DeleteContactRequest) GetContactId() string {
	if m != nil {
		return m.ContactId
	}
	return ""
}

type GetContactRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ContactId            string   `protobuf:"bytes,2,opt,name=contact_id,json=contactId,proto3" json:"contact_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetContactRequest) Reset()         { *m = GetContactRequest{} }
func (m *GetContactRequest) String() string { return proto.CompactTextString(m) }
func (*GetContactRequest) ProtoMessage()    {}
func (*GetContactRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{11}
}

func (m *GetContactRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetContactRequest.Unmarshal(m, b)
}
func (m *GetContactRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetContactRequest.Marshal(b, m, deterministic)
}
func (m *GetContactRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetContactRequest.Merge(m, src)
}
func (m *GetContactRequest) XXX_Size() int {
	return xxx_messageInfo_GetContactRequest.Size(m)
}
func (m *GetContactRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetContactRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetContactRequest proto.InternalMessageInfo

func (m *GetContactRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *GetContactRequest) GetContactId() string {
	if m != nil {
		return m.ContactId
	}
	return ""
}

type GetContactResponse struct {
	Contact              *User    `protobuf:"bytes,1,opt,name=contact,proto3" json:"contact,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetContactResponse) Reset()         { *m = GetContactResponse{} }
func (m *GetContactResponse) String() string { return proto.CompactTextString(m) }
func (*GetContactResponse) ProtoMessage()    {}
func (*GetContactResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{12}
}

func (m *GetContactResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetContactResponse.Unmarshal(m, b)
}
func (m *GetContactResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetContactResponse.Marshal(b, m, deterministic)
}
func (m *GetContactResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetContactResponse.Merge(m, src)
}
func (m *GetContactResponse) XXX_Size() int {
	return xxx_messageInfo_GetContactResponse.Size(m)
}
func (m *GetContactResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetContactResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetContactResponse proto.InternalMessageInfo

func (m *GetContactResponse) GetContact() *User {
	if m != nil {
		return m.Contact
	}
	return nil
}

type ListBillsRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ContactId            string   `protobuf:"bytes,2,opt,name=contact_id,json=contactId,proto3" json:"contact_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListBillsRequest) Reset()         { *m = ListBillsRequest{} }
func (m *ListBillsRequest) String() string { return proto.CompactTextString(m) }
func (*ListBillsRequest) ProtoMessage()    {}
func (*ListBillsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{13}
}

func (m *ListBillsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBillsRequest.Unmarshal(m, b)
}
func (m *ListBillsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBillsRequest.Marshal(b, m, deterministic)
}
func (m *ListBillsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBillsRequest.Merge(m, src)
}
func (m *ListBillsRequest) XXX_Size() int {
	return xxx_messageInfo_ListBillsRequest.Size(m)
}
func (m *ListBillsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBillsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListBillsRequest proto.InternalMessageInfo

func (m *ListBillsRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *ListBillsRequest) GetContactId() string {
	if m != nil {
		return m.ContactId
	}
	return ""
}

type ListBillsResponse struct {
	Bills                []*Bill  `protobuf:"bytes,1,rep,name=bills,proto3" json:"bills,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListBillsResponse) Reset()         { *m = ListBillsResponse{} }
func (m *ListBillsResponse) String() string { return proto.CompactTextString(m) }
func (*ListBillsResponse) ProtoMessage()    {}
func (*ListBillsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{14}
}

func (m *ListBillsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListBillsResponse.Unmarshal(m, b)
}
func (m *ListBillsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListBillsResponse.Marshal(b, m, deterministic)
}
func (m *ListBillsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListBillsResponse.Merge(m, src)
}
func (m *ListBillsResponse) XXX_Size() int {
	return xxx_messageInfo_ListBillsResponse.Size(m)
}
func (m *ListBillsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListBillsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListBillsResponse proto.InternalMessageInfo

func (m *ListBillsResponse) GetBills() []*Bill {
	if m != nil {
		return m.Bills
	}
	return nil
}

type CreateBillRequest struct {
	Bill                 *Bill    `protobuf:"bytes,1,opt,name=bill,proto3" json:"bill,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateBillRequest) Reset()         { *m = CreateBillRequest{} }
func (m *CreateBillRequest) String() string { return proto.CompactTextString(m) }
func (*CreateBillRequest) ProtoMessage()    {}
func (*CreateBillRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{15}
}

func (m *CreateBillRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBillRequest.Unmarshal(m, b)
}
func (m *CreateBillRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBillRequest.Marshal(b, m, deterministic)
}
func (m *CreateBillRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBillRequest.Merge(m, src)
}
func (m *CreateBillRequest) XXX_Size() int {
	return xxx_messageInfo_CreateBillRequest.Size(m)
}
func (m *CreateBillRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBillRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBillRequest proto.InternalMessageInfo

func (m *CreateBillRequest) GetBill() *Bill {
	if m != nil {
		return m.Bill
	}
	return nil
}

type CreateBillResponse struct {
	Bill                 *Bill    `protobuf:"bytes,1,opt,name=bill,proto3" json:"bill,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateBillResponse) Reset()         { *m = CreateBillResponse{} }
func (m *CreateBillResponse) String() string { return proto.CompactTextString(m) }
func (*CreateBillResponse) ProtoMessage()    {}
func (*CreateBillResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{16}
}

func (m *CreateBillResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBillResponse.Unmarshal(m, b)
}
func (m *CreateBillResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBillResponse.Marshal(b, m, deterministic)
}
func (m *CreateBillResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBillResponse.Merge(m, src)
}
func (m *CreateBillResponse) XXX_Size() int {
	return xxx_messageInfo_CreateBillResponse.Size(m)
}
func (m *CreateBillResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBillResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBillResponse proto.InternalMessageInfo

func (m *CreateBillResponse) GetBill() *Bill {
	if m != nil {
		return m.Bill
	}
	return nil
}

type UpdateBillRequest struct {
	Bill                 *Bill    `protobuf:"bytes,1,opt,name=bill,proto3" json:"bill,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateBillRequest) Reset()         { *m = UpdateBillRequest{} }
func (m *UpdateBillRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateBillRequest) ProtoMessage()    {}
func (*UpdateBillRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{17}
}

func (m *UpdateBillRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateBillRequest.Unmarshal(m, b)
}
func (m *UpdateBillRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateBillRequest.Marshal(b, m, deterministic)
}
func (m *UpdateBillRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateBillRequest.Merge(m, src)
}
func (m *UpdateBillRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateBillRequest.Size(m)
}
func (m *UpdateBillRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateBillRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateBillRequest proto.InternalMessageInfo

func (m *UpdateBillRequest) GetBill() *Bill {
	if m != nil {
		return m.Bill
	}
	return nil
}

type UpdateBillResponse struct {
	Bill                 *Bill    `protobuf:"bytes,1,opt,name=bill,proto3" json:"bill,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateBillResponse) Reset()         { *m = UpdateBillResponse{} }
func (m *UpdateBillResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateBillResponse) ProtoMessage()    {}
func (*UpdateBillResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{18}
}

func (m *UpdateBillResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateBillResponse.Unmarshal(m, b)
}
func (m *UpdateBillResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateBillResponse.Marshal(b, m, deterministic)
}
func (m *UpdateBillResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateBillResponse.Merge(m, src)
}
func (m *UpdateBillResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateBillResponse.Size(m)
}
func (m *UpdateBillResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateBillResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateBillResponse proto.InternalMessageInfo

func (m *UpdateBillResponse) GetBill() *Bill {
	if m != nil {
		return m.Bill
	}
	return nil
}

type DeleteBillRequest struct {
	BillId               string   `protobuf:"bytes,1,opt,name=bill_id,json=billId,proto3" json:"bill_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteBillRequest) Reset()         { *m = DeleteBillRequest{} }
func (m *DeleteBillRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteBillRequest) ProtoMessage()    {}
func (*DeleteBillRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{19}
}

func (m *DeleteBillRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteBillRequest.Unmarshal(m, b)
}
func (m *DeleteBillRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteBillRequest.Marshal(b, m, deterministic)
}
func (m *DeleteBillRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteBillRequest.Merge(m, src)
}
func (m *DeleteBillRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteBillRequest.Size(m)
}
func (m *DeleteBillRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteBillRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteBillRequest proto.InternalMessageInfo

func (m *DeleteBillRequest) GetBillId() string {
	if m != nil {
		return m.BillId
	}
	return ""
}

type CreateUserRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{20}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type CreateUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserResponse) Reset()         { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()    {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{21}
}

func (m *CreateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResponse.Unmarshal(m, b)
}
func (m *CreateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResponse.Marshal(b, m, deterministic)
}
func (m *CreateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResponse.Merge(m, src)
}
func (m *CreateUserResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUserResponse.Size(m)
}
func (m *CreateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResponse proto.InternalMessageInfo

func (m *CreateUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UpdateUserRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserRequest) Reset()         { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()    {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{22}
}

func (m *UpdateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserRequest.Unmarshal(m, b)
}
func (m *UpdateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserRequest.Merge(m, src)
}
func (m *UpdateUserRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserRequest.Size(m)
}
func (m *UpdateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserRequest proto.InternalMessageInfo

func (m *UpdateUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *UpdateUserRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type UpdateUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserResponse) Reset()         { *m = UpdateUserResponse{} }
func (m *UpdateUserResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateUserResponse) ProtoMessage()    {}
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{23}
}

func (m *UpdateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserResponse.Unmarshal(m, b)
}
func (m *UpdateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserResponse.Marshal(b, m, deterministic)
}
func (m *UpdateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserResponse.Merge(m, src)
}
func (m *UpdateUserResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateUserResponse.Size(m)
}
func (m *UpdateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserResponse proto.InternalMessageInfo

func (m *UpdateUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type DeleteUserRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserRequest) Reset()         { *m = DeleteUserRequest{} }
func (m *DeleteUserRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteUserRequest) ProtoMessage()    {}
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{24}
}

func (m *DeleteUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserRequest.Unmarshal(m, b)
}
func (m *DeleteUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserRequest.Marshal(b, m, deterministic)
}
func (m *DeleteUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserRequest.Merge(m, src)
}
func (m *DeleteUserRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteUserRequest.Size(m)
}
func (m *DeleteUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserRequest proto.InternalMessageInfo

func (m *DeleteUserRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type GetUserRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{25}
}

func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (m *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(m, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type GetUserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserResponse) Reset()         { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()    {}
func (*GetUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{26}
}

func (m *GetUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserResponse.Unmarshal(m, b)
}
func (m *GetUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserResponse.Marshal(b, m, deterministic)
}
func (m *GetUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserResponse.Merge(m, src)
}
func (m *GetUserResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserResponse.Size(m)
}
func (m *GetUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserResponse proto.InternalMessageInfo

func (m *GetUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type GetBillRequest struct {
	BillId               string   `protobuf:"bytes,1,opt,name=bill_id,json=billId,proto3" json:"bill_id,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBillRequest) Reset()         { *m = GetBillRequest{} }
func (m *GetBillRequest) String() string { return proto.CompactTextString(m) }
func (*GetBillRequest) ProtoMessage()    {}
func (*GetBillRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{27}
}

func (m *GetBillRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBillRequest.Unmarshal(m, b)
}
func (m *GetBillRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBillRequest.Marshal(b, m, deterministic)
}
func (m *GetBillRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBillRequest.Merge(m, src)
}
func (m *GetBillRequest) XXX_Size() int {
	return xxx_messageInfo_GetBillRequest.Size(m)
}
func (m *GetBillRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBillRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBillRequest proto.InternalMessageInfo

func (m *GetBillRequest) GetBillId() string {
	if m != nil {
		return m.BillId
	}
	return ""
}

func (m *GetBillRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type GetBillResponse struct {
	Bill                 *Bill    `protobuf:"bytes,1,opt,name=bill,proto3" json:"bill,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBillResponse) Reset()         { *m = GetBillResponse{} }
func (m *GetBillResponse) String() string { return proto.CompactTextString(m) }
func (*GetBillResponse) ProtoMessage()    {}
func (*GetBillResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{28}
}

func (m *GetBillResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBillResponse.Unmarshal(m, b)
}
func (m *GetBillResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBillResponse.Marshal(b, m, deterministic)
}
func (m *GetBillResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBillResponse.Merge(m, src)
}
func (m *GetBillResponse) XXX_Size() int {
	return xxx_messageInfo_GetBillResponse.Size(m)
}
func (m *GetBillResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBillResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBillResponse proto.InternalMessageInfo

func (m *GetBillResponse) GetBill() *Bill {
	if m != nil {
		return m.Bill
	}
	return nil
}

type GetUserByMobileRequest struct {
	Mobile               string   `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserByMobileRequest) Reset()         { *m = GetUserByMobileRequest{} }
func (m *GetUserByMobileRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserByMobileRequest) ProtoMessage()    {}
func (*GetUserByMobileRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{29}
}

func (m *GetUserByMobileRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserByMobileRequest.Unmarshal(m, b)
}
func (m *GetUserByMobileRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserByMobileRequest.Marshal(b, m, deterministic)
}
func (m *GetUserByMobileRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserByMobileRequest.Merge(m, src)
}
func (m *GetUserByMobileRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserByMobileRequest.Size(m)
}
func (m *GetUserByMobileRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserByMobileRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserByMobileRequest proto.InternalMessageInfo

func (m *GetUserByMobileRequest) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

type GetUserByMobileResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserByMobileResponse) Reset()         { *m = GetUserByMobileResponse{} }
func (m *GetUserByMobileResponse) String() string { return proto.CompactTextString(m) }
func (*GetUserByMobileResponse) ProtoMessage()    {}
func (*GetUserByMobileResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{30}
}

func (m *GetUserByMobileResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserByMobileResponse.Unmarshal(m, b)
}
func (m *GetUserByMobileResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserByMobileResponse.Marshal(b, m, deterministic)
}
func (m *GetUserByMobileResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserByMobileResponse.Merge(m, src)
}
func (m *GetUserByMobileResponse) XXX_Size() int {
	return xxx_messageInfo_GetUserByMobileResponse.Size(m)
}
func (m *GetUserByMobileResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserByMobileResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserByMobileResponse proto.InternalMessageInfo

func (m *GetUserByMobileResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type LoginRequest struct {
	Mobile               string   `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{31}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetMobile() string {
	if m != nil {
		return m.Mobile
	}
	return ""
}

func (m *LoginRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type LoginResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{32}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func init() {
	proto.RegisterEnum("okcredit.billscan.v1.Agreement_Status", Agreement_Status_name, Agreement_Status_value)
	proto.RegisterType((*Relation)(nil), "okcredit.billscan.v1.Relation")
	proto.RegisterType((*Relation_Profile)(nil), "okcredit.billscan.v1.Relation.Profile")
	proto.RegisterType((*User)(nil), "okcredit.billscan.v1.User")
	proto.RegisterType((*Bill)(nil), "okcredit.billscan.v1.Bill")
	proto.RegisterType((*Agreement)(nil), "okcredit.billscan.v1.Agreement")
	proto.RegisterType((*ListContactsRequest)(nil), "okcredit.billscan.v1.ListContactsRequest")
	proto.RegisterType((*ListContactsResponse)(nil), "okcredit.billscan.v1.ListContactsResponse")
	proto.RegisterType((*AddContactRequest)(nil), "okcredit.billscan.v1.AddContactRequest")
	proto.RegisterType((*AddContactResponse)(nil), "okcredit.billscan.v1.AddContactResponse")
	proto.RegisterType((*UpdateContactRequest)(nil), "okcredit.billscan.v1.UpdateContactRequest")
	proto.RegisterType((*UpdateContactResponse)(nil), "okcredit.billscan.v1.UpdateContactResponse")
	proto.RegisterType((*DeleteContactRequest)(nil), "okcredit.billscan.v1.DeleteContactRequest")
	proto.RegisterType((*GetContactRequest)(nil), "okcredit.billscan.v1.GetContactRequest")
	proto.RegisterType((*GetContactResponse)(nil), "okcredit.billscan.v1.GetContactResponse")
	proto.RegisterType((*ListBillsRequest)(nil), "okcredit.billscan.v1.ListBillsRequest")
	proto.RegisterType((*ListBillsResponse)(nil), "okcredit.billscan.v1.ListBillsResponse")
	proto.RegisterType((*CreateBillRequest)(nil), "okcredit.billscan.v1.CreateBillRequest")
	proto.RegisterType((*CreateBillResponse)(nil), "okcredit.billscan.v1.CreateBillResponse")
	proto.RegisterType((*UpdateBillRequest)(nil), "okcredit.billscan.v1.UpdateBillRequest")
	proto.RegisterType((*UpdateBillResponse)(nil), "okcredit.billscan.v1.UpdateBillResponse")
	proto.RegisterType((*DeleteBillRequest)(nil), "okcredit.billscan.v1.DeleteBillRequest")
	proto.RegisterType((*CreateUserRequest)(nil), "okcredit.billscan.v1.CreateUserRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "okcredit.billscan.v1.CreateUserResponse")
	proto.RegisterType((*UpdateUserRequest)(nil), "okcredit.billscan.v1.UpdateUserRequest")
	proto.RegisterType((*UpdateUserResponse)(nil), "okcredit.billscan.v1.UpdateUserResponse")
	proto.RegisterType((*DeleteUserRequest)(nil), "okcredit.billscan.v1.DeleteUserRequest")
	proto.RegisterType((*GetUserRequest)(nil), "okcredit.billscan.v1.GetUserRequest")
	proto.RegisterType((*GetUserResponse)(nil), "okcredit.billscan.v1.GetUserResponse")
	proto.RegisterType((*GetBillRequest)(nil), "okcredit.billscan.v1.GetBillRequest")
	proto.RegisterType((*GetBillResponse)(nil), "okcredit.billscan.v1.GetBillResponse")
	proto.RegisterType((*GetUserByMobileRequest)(nil), "okcredit.billscan.v1.GetUserByMobileRequest")
	proto.RegisterType((*GetUserByMobileResponse)(nil), "okcredit.billscan.v1.GetUserByMobileResponse")
	proto.RegisterType((*LoginRequest)(nil), "okcredit.billscan.v1.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "okcredit.billscan.v1.LoginResponse")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 1146 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x57, 0xef, 0x72, 0xdb, 0x44,
	0x10, 0x8f, 0x1c, 0x47, 0xb6, 0xd7, 0x49, 0x1a, 0x1f, 0x21, 0xcd, 0xa8, 0xd3, 0x12, 0x54, 0xda,
	0xba, 0x10, 0xe4, 0x92, 0x32, 0x7c, 0x80, 0x01, 0xc6, 0xb1, 0x4d, 0xc6, 0x69, 0xea, 0x64, 0x04,
	0x19, 0x18, 0x86, 0xc1, 0x23, 0x5b, 0x17, 0x21, 0x90, 0x2d, 0x21, 0x9d, 0x61, 0xf2, 0x14, 0x7c,
	0xe1, 0x19, 0x79, 0x01, 0x1e, 0x00, 0xe6, 0x4e, 0x27, 0xe9, 0x22, 0x59, 0xb2, 0x6b, 0xc3, 0x37,
	0xdf, 0xfe, 0xfd, 0xed, 0xef, 0x56, 0x7b, 0x6b, 0xa8, 0x19, 0x9e, 0xad, 0x79, 0xbe, 0x4b, 0x5c,
	0xb4, 0xef, 0xfe, 0x32, 0xf6, 0xb1, 0x69, 0x13, 0x6d, 0x64, 0x3b, 0x4e, 0x30, 0x36, 0xa6, 0xda,
	0x6f, 0x1f, 0x29, 0x8f, 0x2c, 0xd7, 0xb5, 0x1c, 0xdc, 0x62, 0x36, 0xa3, 0xd9, 0x4d, 0xeb, 0x77,
	0xdf, 0xf0, 0x3c, 0xec, 0x07, 0xa1, 0x97, 0xf2, 0x20, 0xad, 0xc7, 0x13, 0x8f, 0xdc, 0x86, 0x4a,
	0xf5, 0x8f, 0x12, 0x54, 0x75, 0xec, 0x18, 0xc4, 0x76, 0xa7, 0x68, 0x17, 0x4a, 0xb6, 0x79, 0x28,
	0x1d, 0x49, 0xcd, 0x9a, 0x5e, 0xb2, 0x4d, 0x74, 0x1f, 0x2a, 0xb3, 0x00, 0xfb, 0x43, 0xdb, 0x3c,
	0x2c, 0x31, 0xa1, 0x4c, 0x8f, 0x7d, 0x13, 0x3d, 0x04, 0x18, 0xbb, 0x53, 0x62, 0x8c, 0x09, 0xd5,
	0x6d, 0x32, 0x5d, 0x8d, 0x4b, 0xb8, 0xda, 0xc7, 0x06, 0xc1, 0xe6, 0xd0, 0x20, 0x87, 0xe5, 0x23,
	0xa9, 0x59, 0xd6, 0x6b, 0x5c, 0xd2, 0x26, 0x54, 0x3d, 0xf3, 0xcc, 0x48, 0xbd, 0x15, 0xaa, 0xb9,
	0xa4, 0x4d, 0xd0, 0x25, 0xdc, 0x8b, 0x82, 0x7b, 0xbe, 0x7b, 0x63, 0x3b, 0xf8, 0x50, 0x3e, 0x92,
	0x9a, 0xf5, 0x93, 0xa7, 0xda, 0xbc, 0xfa, 0xb5, 0x08, 0xbe, 0x76, 0x15, 0x5a, 0xeb, 0xbb, 0xdc,
	0x9d, 0x9f, 0x95, 0x63, 0xa8, 0xf0, 0x9f, 0xe8, 0x5d, 0xd8, 0x36, 0xed, 0xc0, 0x73, 0x8c, 0xdb,
	0xe1, 0xd4, 0x98, 0x60, 0x5e, 0x6b, 0x9d, 0xcb, 0x06, 0xc6, 0x04, 0xab, 0x7f, 0x4b, 0x50, 0xbe,
	0x0e, 0xb0, 0x9f, 0x61, 0xe3, 0x00, 0xe4, 0x89, 0x3b, 0xa2, 0x70, 0x38, 0x19, 0xe1, 0x09, 0x3d,
	0x86, 0x1d, 0x8e, 0x73, 0x68, 0x4f, 0x0c, 0x0b, 0x73, 0x3e, 0xb6, 0xb9, 0xb0, 0x4f, 0x65, 0x99,
	0xc4, 0xe5, 0x4c, 0x62, 0xf4, 0x08, 0xc0, 0xc7, 0x96, 0x1d, 0x10, 0xec, 0x63, 0x93, 0xd1, 0x52,
	0xd5, 0x05, 0x49, 0x8a, 0x55, 0xb9, 0x98, 0xd5, 0x4a, 0x9a, 0xd5, 0x87, 0x00, 0x81, 0x6d, 0x4d,
	0x39, 0xc4, 0x6a, 0x78, 0x65, 0x54, 0xc2, 0xf0, 0xa9, 0x7f, 0x49, 0x50, 0x3e, 0xb5, 0x1d, 0x27,
	0x53, 0xf5, 0x03, 0xa8, 0x31, 0x97, 0xe1, 0xcc, 0x77, 0x78, 0xe1, 0x55, 0x26, 0xb8, 0xf6, 0x1d,
	0xaa, 0xa4, 0x37, 0x31, 0xbc, 0xf1, 0xdd, 0x09, 0x2f, 0xbb, 0x4a, 0x05, 0x5f, 0xf9, 0xee, 0x84,
	0x76, 0x0f, 0x53, 0x12, 0x97, 0x57, 0x2b, 0xd3, 0xe3, 0x37, 0x6e, 0xaa, 0x90, 0xad, 0xe2, 0x42,
	0xe4, 0x74, 0x21, 0x9f, 0x43, 0xcd, 0xb0, 0x7c, 0x8c, 0x27, 0x78, 0x1a, 0x96, 0x59, 0x3f, 0x79,
	0x67, 0x7e, 0x63, 0xb4, 0x23, 0x33, 0x3d, 0xf1, 0x50, 0xff, 0x94, 0xa0, 0x16, 0x2b, 0x10, 0x82,
	0xf2, 0xd4, 0x25, 0x51, 0x1f, 0xb0, 0xdf, 0xe8, 0x0b, 0x90, 0x03, 0x62, 0x90, 0x59, 0xc0, 0xca,
	0xdd, 0xcd, 0x6b, 0xbb, 0x38, 0x88, 0xf6, 0x35, 0xb3, 0xd6, 0xb9, 0x97, 0xfa, 0x12, 0xe4, 0x50,
	0x82, 0xea, 0x50, 0xb9, 0xea, 0x0d, 0xba, 0xfd, 0xc1, 0xd9, 0xde, 0x06, 0xda, 0x83, 0xed, 0x76,
	0xe7, 0xd5, 0xe0, 0xf2, 0xdb, 0x8b, 0x5e, 0xf7, 0xac, 0xd7, 0xdd, 0x93, 0x10, 0x80, 0xdc, 0xed,
	0x0d, 0xfa, 0xbd, 0xee, 0x5e, 0x49, 0xd5, 0xe0, 0xad, 0x0b, 0x3b, 0x20, 0x9d, 0xb0, 0x73, 0x03,
	0x1d, 0xff, 0x3a, 0xc3, 0x01, 0x11, 0xbf, 0x40, 0x49, 0xfc, 0x02, 0xd5, 0x01, 0xec, 0xdf, 0xb5,
	0x0f, 0x3c, 0x77, 0x1a, 0x60, 0xf4, 0x09, 0x54, 0x79, 0xf7, 0x07, 0x87, 0xd2, 0xd1, 0x66, 0xb3,
	0x7e, 0xa2, 0xcc, 0x87, 0x4f, 0x5b, 0x5c, 0x8f, 0x6d, 0xd5, 0x11, 0x34, 0xda, 0xa6, 0xc9, 0xc3,
	0x45, 0xd9, 0x3f, 0x86, 0x0a, 0x37, 0x60, 0xd9, 0x8b, 0x63, 0x45, 0xa6, 0xb9, 0x53, 0x43, 0x3d,
	0x07, 0x24, 0xe6, 0xe0, 0x88, 0x57, 0x4a, 0xa2, 0x62, 0xd8, 0xbf, 0x66, 0x2d, 0xf1, 0xff, 0x42,
	0x7e, 0x0d, 0x6f, 0xa7, 0xd2, 0xac, 0x85, 0x7a, 0x00, 0xfb, 0x5d, 0xec, 0xe0, 0x0c, 0xea, 0xbc,
	0x6b, 0x4e, 0x0d, 0xda, 0x52, 0x6a, 0xd0, 0xaa, 0xaf, 0xa0, 0x71, 0x86, 0xc9, 0x7f, 0x14, 0xec,
	0x1c, 0x90, 0x18, 0x6c, 0xad, 0x42, 0xcf, 0x61, 0x8f, 0xb6, 0x27, 0x9d, 0x28, 0xc1, 0xba, 0xb8,
	0x7a, 0xd0, 0x10, 0x62, 0x71, 0x58, 0x2f, 0x60, 0x8b, 0x65, 0x2f, 0x6e, 0x72, 0xea, 0xa3, 0x87,
	0x86, 0x6a, 0x07, 0x1a, 0x1d, 0x36, 0x63, 0x98, 0x90, 0x63, 0xd2, 0xa0, 0x4c, 0xb5, 0xc5, 0xa5,
	0x31, 0x07, 0x66, 0xa7, 0x76, 0x01, 0x89, 0x41, 0x38, 0x98, 0x37, 0x8d, 0xd2, 0x81, 0x46, 0xd8,
	0x55, 0x6b, 0x42, 0x11, 0x83, 0xac, 0x08, 0xe5, 0x18, 0x1a, 0x61, 0x47, 0x8a, 0x50, 0xa2, 0xc9,
	0x9d, 0xdc, 0x14, 0x3d, 0xf6, 0xcd, 0x84, 0x43, 0x76, 0xdb, 0x09, 0x70, 0x7a, 0x91, 0x4b, 0xb4,
	0x07, 0xb3, 0x4b, 0x38, 0x0c, 0x83, 0x24, 0xc0, 0xdf, 0x28, 0xca, 0x0f, 0x11, 0x87, 0x6b, 0x40,
	0xc9, 0xff, 0xee, 0x63, 0x72, 0xd7, 0xc2, 0x18, 0x93, 0x2b, 0x62, 0xcc, 0x1d, 0xe9, 0xcf, 0x61,
	0xf7, 0x0c, 0x93, 0xa5, 0x4c, 0xdb, 0x70, 0x2f, 0x36, 0x5d, 0x11, 0xdb, 0x29, 0xcb, 0xb6, 0xcc,
	0xad, 0xe7, 0xb3, 0x14, 0xc2, 0x58, 0xab, 0xff, 0x5e, 0xc0, 0x01, 0xaf, 0xe4, 0xf4, 0xf6, 0x35,
	0xdb, 0xa7, 0x22, 0x38, 0xc9, 0xba, 0x25, 0x89, 0xeb, 0x96, 0xda, 0x87, 0xfb, 0x19, 0x8f, 0x15,
	0x39, 0xf8, 0x14, 0xb6, 0x2f, 0x5c, 0xcb, 0x9e, 0x2e, 0x48, 0xc9, 0xb6, 0x04, 0xba, 0xb4, 0x95,
	0xf8, 0x96, 0x40, 0xd7, 0xc4, 0x2f, 0x61, 0x87, 0xfb, 0xae, 0x96, 0xfc, 0xe4, 0x9f, 0x3a, 0x6c,
	0xb6, 0xaf, 0xfa, 0xc8, 0x82, 0x6d, 0xf1, 0x25, 0x47, 0xcf, 0xe7, 0x7b, 0xce, 0xd9, 0x0e, 0x94,
	0xf7, 0x97, 0x31, 0x0d, 0xe1, 0xa9, 0x1b, 0xc8, 0x00, 0x48, 0xe6, 0x3b, 0x7a, 0x36, 0xdf, 0x37,
	0xf3, 0x9c, 0x28, 0xcd, 0xc5, 0x86, 0x62, 0x8a, 0xe4, 0x85, 0xcf, 0x4b, 0x91, 0xd9, 0x33, 0xf2,
	0x52, 0x64, 0x97, 0x05, 0x75, 0x03, 0xfd, 0x0c, 0x3b, 0x77, 0x5e, 0x64, 0x94, 0x43, 0xc2, 0xbc,
	0xed, 0x40, 0xf9, 0x60, 0x29, 0xdb, 0x38, 0xd7, 0x35, 0xec, 0xdc, 0x79, 0xae, 0xf3, 0x72, 0xcd,
	0x7b, 0xd3, 0x95, 0x03, 0x2d, 0xfc, 0xdf, 0xa5, 0x45, 0xff, 0xbb, 0xb4, 0x1e, 0xfd, 0xdf, 0xa5,
	0x6e, 0xa0, 0xef, 0xa0, 0xc2, 0x3b, 0x18, 0xbd, 0x97, 0x4b, 0xae, 0x30, 0x07, 0x94, 0x27, 0x0b,
	0xac, 0x44, 0xfe, 0x93, 0xd1, 0x9a, 0xc7, 0x7f, 0x66, 0x82, 0xe7, 0xf1, 0x9f, 0x9d, 0xd2, 0x61,
	0x8a, 0x64, 0x32, 0xe6, 0xa5, 0xc8, 0x4c, 0xe6, 0xbc, 0x14, 0xd9, 0x21, 0xab, 0x6e, 0xa0, 0x4b,
	0x80, 0x64, 0x6c, 0xe6, 0xa5, 0xc8, 0x0c, 0xd6, 0x02, 0xc2, 0x7f, 0x84, 0x5a, 0xbc, 0x41, 0xa0,
	0xa7, 0xf9, 0x1f, 0x8d, 0xb8, 0xae, 0x28, 0xcf, 0x16, 0xda, 0x65, 0x69, 0x67, 0xff, 0xa0, 0x0a,
	0x69, 0x17, 0x06, 0x6e, 0x31, 0xed, 0xe2, 0x54, 0x8d, 0x7b, 0x86, 0xc5, 0xcf, 0xef, 0x19, 0x31,
	0xf8, 0x93, 0x05, 0x56, 0xd9, 0x0b, 0x2d, 0x02, 0x9f, 0x59, 0x57, 0x8a, 0x2f, 0x34, 0x95, 0x22,
	0xbe, 0xd0, 0xa2, 0x14, 0x99, 0x35, 0xa4, 0xe0, 0x42, 0xbd, 0xf8, 0xfd, 0x8b, 0xde, 0x00, 0x74,
	0x5c, 0xf8, 0x8d, 0xa4, 0x1e, 0x17, 0xe5, 0xc3, 0x25, 0xad, 0xe3, 0x12, 0x74, 0xd8, 0x72, 0xe8,
	0xb8, 0x47, 0x6a, 0x4e, 0x5b, 0x08, 0xef, 0x88, 0xf2, 0xb8, 0xd0, 0x26, 0x8a, 0x79, 0xaa, 0x7d,
	0x7f, 0x6c, 0xd9, 0xe4, 0xa7, 0xd9, 0x48, 0x1b, 0xbb, 0x93, 0x56, 0xe4, 0xd2, 0x8a, 0x5c, 0x5a,
	0x86, 0x67, 0xb7, 0x2c, 0xf7, 0xb3, 0xe8, 0x3c, 0x92, 0x19, 0x0f, 0x2f, 0xff, 0x0d, 0x00, 0x00,
	0xff, 0xff, 0x74, 0x61, 0x7b, 0x99, 0x12, 0x12, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// APIClient is the client API for API service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type APIClient interface {
	ListContacts(ctx context.Context, in *ListContactsRequest, opts ...grpc.CallOption) (*ListContactsResponse, error)
	GetContact(ctx context.Context, in *GetContactRequest, opts ...grpc.CallOption) (*GetContactResponse, error)
	AddContact(ctx context.Context, in *AddContactRequest, opts ...grpc.CallOption) (*AddContactResponse, error)
	UpdateContact(ctx context.Context, in *UpdateContactRequest, opts ...grpc.CallOption) (*UpdateContactResponse, error)
	DeleteContact(ctx context.Context, in *DeleteContactRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error)
	DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	ListBills(ctx context.Context, in *ListBillsRequest, opts ...grpc.CallOption) (*ListBillsResponse, error)
	CreateBill(ctx context.Context, in *CreateBillRequest, opts ...grpc.CallOption) (*CreateBillResponse, error)
	GetBill(ctx context.Context, in *GetBillRequest, opts ...grpc.CallOption) (*GetBillResponse, error)
	UpdateBill(ctx context.Context, in *UpdateBillRequest, opts ...grpc.CallOption) (*UpdateBillResponse, error)
	DeleteBill(ctx context.Context, in *DeleteBillRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	GetUserByMobile(ctx context.Context, in *GetUserByMobileRequest, opts ...grpc.CallOption) (*GetUserByMobileResponse, error)
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
}

type aPIClient struct {
	cc *grpc.ClientConn
}

func NewAPIClient(cc *grpc.ClientConn) APIClient {
	return &aPIClient{cc}
}

func (c *aPIClient) ListContacts(ctx context.Context, in *ListContactsRequest, opts ...grpc.CallOption) (*ListContactsResponse, error) {
	out := new(ListContactsResponse)
	err := c.cc.Invoke(ctx, "/okcredit.billscan.v1.API/ListContacts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) GetContact(ctx context.Context, in *GetContactRequest, opts ...grpc.CallOption) (*GetContactResponse, error) {
	out := new(GetContactResponse)
	err := c.cc.Invoke(ctx, "/okcredit.billscan.v1.API/GetContact", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) AddContact(ctx context.Context, in *AddContactRequest, opts ...grpc.CallOption) (*AddContactResponse, error) {
	out := new(AddContactResponse)
	err := c.cc.Invoke(ctx, "/okcredit.billscan.v1.API/AddContact", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) UpdateContact(ctx context.Context, in *UpdateContactRequest, opts ...grpc.CallOption) (*UpdateContactResponse, error) {
	out := new(UpdateContactResponse)
	err := c.cc.Invoke(ctx, "/okcredit.billscan.v1.API/UpdateContact", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) DeleteContact(ctx context.Context, in *DeleteContactRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/okcredit.billscan.v1.API/DeleteContact", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	out := new(GetUserResponse)
	err := c.cc.Invoke(ctx, "/okcredit.billscan.v1.API/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, "/okcredit.billscan.v1.API/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error) {
	out := new(UpdateUserResponse)
	err := c.cc.Invoke(ctx, "/okcredit.billscan.v1.API/UpdateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/okcredit.billscan.v1.API/DeleteUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) ListBills(ctx context.Context, in *ListBillsRequest, opts ...grpc.CallOption) (*ListBillsResponse, error) {
	out := new(ListBillsResponse)
	err := c.cc.Invoke(ctx, "/okcredit.billscan.v1.API/ListBills", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) CreateBill(ctx context.Context, in *CreateBillRequest, opts ...grpc.CallOption) (*CreateBillResponse, error) {
	out := new(CreateBillResponse)
	err := c.cc.Invoke(ctx, "/okcredit.billscan.v1.API/CreateBill", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) GetBill(ctx context.Context, in *GetBillRequest, opts ...grpc.CallOption) (*GetBillResponse, error) {
	out := new(GetBillResponse)
	err := c.cc.Invoke(ctx, "/okcredit.billscan.v1.API/GetBill", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) UpdateBill(ctx context.Context, in *UpdateBillRequest, opts ...grpc.CallOption) (*UpdateBillResponse, error) {
	out := new(UpdateBillResponse)
	err := c.cc.Invoke(ctx, "/okcredit.billscan.v1.API/UpdateBill", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) DeleteBill(ctx context.Context, in *DeleteBillRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/okcredit.billscan.v1.API/DeleteBill", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) GetUserByMobile(ctx context.Context, in *GetUserByMobileRequest, opts ...grpc.CallOption) (*GetUserByMobileResponse, error) {
	out := new(GetUserByMobileResponse)
	err := c.cc.Invoke(ctx, "/okcredit.billscan.v1.API/GetUserByMobile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/okcredit.billscan.v1.API/login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// APIServer is the server API for API service.
type APIServer interface {
	ListContacts(context.Context, *ListContactsRequest) (*ListContactsResponse, error)
	GetContact(context.Context, *GetContactRequest) (*GetContactResponse, error)
	AddContact(context.Context, *AddContactRequest) (*AddContactResponse, error)
	UpdateContact(context.Context, *UpdateContactRequest) (*UpdateContactResponse, error)
	DeleteContact(context.Context, *DeleteContactRequest) (*empty.Empty, error)
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
	CreateUser(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	UpdateUser(context.Context, *UpdateUserRequest) (*UpdateUserResponse, error)
	DeleteUser(context.Context, *DeleteUserRequest) (*empty.Empty, error)
	ListBills(context.Context, *ListBillsRequest) (*ListBillsResponse, error)
	CreateBill(context.Context, *CreateBillRequest) (*CreateBillResponse, error)
	GetBill(context.Context, *GetBillRequest) (*GetBillResponse, error)
	UpdateBill(context.Context, *UpdateBillRequest) (*UpdateBillResponse, error)
	DeleteBill(context.Context, *DeleteBillRequest) (*empty.Empty, error)
	GetUserByMobile(context.Context, *GetUserByMobileRequest) (*GetUserByMobileResponse, error)
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
}

// UnimplementedAPIServer can be embedded to have forward compatible implementations.
type UnimplementedAPIServer struct {
}

func (*UnimplementedAPIServer) ListContacts(ctx context.Context, req *ListContactsRequest) (*ListContactsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListContacts not implemented")
}
func (*UnimplementedAPIServer) GetContact(ctx context.Context, req *GetContactRequest) (*GetContactResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetContact not implemented")
}
func (*UnimplementedAPIServer) AddContact(ctx context.Context, req *AddContactRequest) (*AddContactResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddContact not implemented")
}
func (*UnimplementedAPIServer) UpdateContact(ctx context.Context, req *UpdateContactRequest) (*UpdateContactResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateContact not implemented")
}
func (*UnimplementedAPIServer) DeleteContact(ctx context.Context, req *DeleteContactRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteContact not implemented")
}
func (*UnimplementedAPIServer) GetUser(ctx context.Context, req *GetUserRequest) (*GetUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (*UnimplementedAPIServer) CreateUser(ctx context.Context, req *CreateUserRequest) (*CreateUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateUser not implemented")
}
func (*UnimplementedAPIServer) UpdateUser(ctx context.Context, req *UpdateUserRequest) (*UpdateUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateUser not implemented")
}
func (*UnimplementedAPIServer) DeleteUser(ctx context.Context, req *DeleteUserRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteUser not implemented")
}
func (*UnimplementedAPIServer) ListBills(ctx context.Context, req *ListBillsRequest) (*ListBillsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBills not implemented")
}
func (*UnimplementedAPIServer) CreateBill(ctx context.Context, req *CreateBillRequest) (*CreateBillResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBill not implemented")
}
func (*UnimplementedAPIServer) GetBill(ctx context.Context, req *GetBillRequest) (*GetBillResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBill not implemented")
}
func (*UnimplementedAPIServer) UpdateBill(ctx context.Context, req *UpdateBillRequest) (*UpdateBillResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBill not implemented")
}
func (*UnimplementedAPIServer) DeleteBill(ctx context.Context, req *DeleteBillRequest) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBill not implemented")
}
func (*UnimplementedAPIServer) GetUserByMobile(ctx context.Context, req *GetUserByMobileRequest) (*GetUserByMobileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserByMobile not implemented")
}
func (*UnimplementedAPIServer) Login(ctx context.Context, req *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}

func RegisterAPIServer(s *grpc.Server, srv APIServer) {
	s.RegisterService(&_API_serviceDesc, srv)
}

func _API_ListContacts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListContactsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).ListContacts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/okcredit.billscan.v1.API/ListContacts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).ListContacts(ctx, req.(*ListContactsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_GetContact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetContact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/okcredit.billscan.v1.API/GetContact",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetContact(ctx, req.(*GetContactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_AddContact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddContactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).AddContact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/okcredit.billscan.v1.API/AddContact",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).AddContact(ctx, req.(*AddContactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_UpdateContact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateContactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).UpdateContact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/okcredit.billscan.v1.API/UpdateContact",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).UpdateContact(ctx, req.(*UpdateContactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_DeleteContact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteContactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).DeleteContact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/okcredit.billscan.v1.API/DeleteContact",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).DeleteContact(ctx, req.(*DeleteContactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/okcredit.billscan.v1.API/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/okcredit.billscan.v1.API/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/okcredit.billscan.v1.API/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).UpdateUser(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_DeleteUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).DeleteUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/okcredit.billscan.v1.API/DeleteUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).DeleteUser(ctx, req.(*DeleteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_ListBills_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBillsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).ListBills(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/okcredit.billscan.v1.API/ListBills",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).ListBills(ctx, req.(*ListBillsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_CreateBill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).CreateBill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/okcredit.billscan.v1.API/CreateBill",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).CreateBill(ctx, req.(*CreateBillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_GetBill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetBill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/okcredit.billscan.v1.API/GetBill",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetBill(ctx, req.(*GetBillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_UpdateBill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).UpdateBill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/okcredit.billscan.v1.API/UpdateBill",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).UpdateBill(ctx, req.(*UpdateBillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_DeleteBill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).DeleteBill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/okcredit.billscan.v1.API/DeleteBill",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).DeleteBill(ctx, req.(*DeleteBillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_GetUserByMobile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserByMobileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).GetUserByMobile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/okcredit.billscan.v1.API/GetUserByMobile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).GetUserByMobile(ctx, req.(*GetUserByMobileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _API_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/okcredit.billscan.v1.API/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _API_serviceDesc = grpc.ServiceDesc{
	ServiceName: "okcredit.billscan.v1.API",
	HandlerType: (*APIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListContacts",
			Handler:    _API_ListContacts_Handler,
		},
		{
			MethodName: "GetContact",
			Handler:    _API_GetContact_Handler,
		},
		{
			MethodName: "AddContact",
			Handler:    _API_AddContact_Handler,
		},
		{
			MethodName: "UpdateContact",
			Handler:    _API_UpdateContact_Handler,
		},
		{
			MethodName: "DeleteContact",
			Handler:    _API_DeleteContact_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _API_GetUser_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _API_CreateUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _API_UpdateUser_Handler,
		},
		{
			MethodName: "DeleteUser",
			Handler:    _API_DeleteUser_Handler,
		},
		{
			MethodName: "ListBills",
			Handler:    _API_ListBills_Handler,
		},
		{
			MethodName: "CreateBill",
			Handler:    _API_CreateBill_Handler,
		},
		{
			MethodName: "GetBill",
			Handler:    _API_GetBill_Handler,
		},
		{
			MethodName: "UpdateBill",
			Handler:    _API_UpdateBill_Handler,
		},
		{
			MethodName: "DeleteBill",
			Handler:    _API_DeleteBill_Handler,
		},
		{
			MethodName: "GetUserByMobile",
			Handler:    _API_GetUserByMobile_Handler,
		},
		{
			MethodName: "login",
			Handler:    _API_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
